server:
  port: 6005
spring:
  application:
    name: API-GATEWAY
    spring: null
  main:
    web-application-type: reactive
  datasource:
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: 'http://localhost:6004/eureka'
      cloud: null
    gateway:
      routes:
        - id: STUDENTINFO-SERVICE
          uri: 'http://172.22.22.189:9002/'
          predicates:
            - Path=/student-service/**
